export default () => ({
  port: process.env.PORT,
  env: process.env.ENV,
  shAdminApiUrl: process.env.SH_ADMIN_API_URL,
  shAdminPanelUrl: process.env.SH_ADMIN_PANEL_URL,
  mysqlDbUrl: process.env.MYSQL_DB_URL,
  mongodbDbUrl: process.env.MONGODB_DB_URL,
  shUserJwtSecret: process.env.SH_USER_JWT_SECRET,
  stripeKey: process.env.STRIPE_KEY,
  stripeSecretKey: process.env.STRIPE_SECRET_KEY,
  chartmogulApiKey: process.env.CHARTMOGUL_API_KEY,
  logApiActivity: process.env.LOG_API_ACTIVITY,
  bypassOtp: process.env.BYPASS_OTP,
  exportEmails: process.env.EXPORT_EMAILS,
  shV2BaseUrl: process.env.SH_V2_BASE_URL,
  shSuperAdminEmail: process.env.SH_SUPER_ADMIN_EMAIL,
  shSuperAdminPassword: process.env.SH_SUPER_ADMIN_PASSWORD,
  shSequenceManagerBaseUrl: process.env.SH_SEQUENCE_MANAGER_BASE_URL,
  shCoreBaseUrl: process.env.SH_CORE_BASE_URL,
  shImapConnectionManagerBaseUrl:
    process.env.SH_IMAP_CONNECTION_MANAGER_BASE_URL,
  shGmailWatchServiceBaseUrl: process.env.SH_GMAIL_WATCH_SERVICE_BASE_URL,
  shSchedulerEventQueueBaseUrl: process.env.SH_SCHEDULER_EVENT_QUEUE_BASE_URL,
  shTokenManagerBaseUrl: process.env.SH_TOKEN_MANAGER_BASE_URL,
  captchaSecretKey: process.env.CAPTCHA_SECRET_KEY,
  postmarkSecretKey: process.env.POSTMARK_SECRET_KEY,
  postmarkFromEmail: process.env.POSTMARK_FROM_EMAIL,
  postmarkFromName: process.env.POSTMARK_FROM_NAME,
  redisHost: process.env.REDIS_HOST,
  redisPort: process.env.REDIS_PORT,
  redisDb: process.env.REDIS_DB,
  redisUsername: process.env.REDIS_USERNAME,
  redisPassword: process.env.REDIS_PASSWORD,
  supportAuthToken: process.env.SUPPORT_AUTH_TOKEN,
  trulyinboxCoreBaseUrl: process.env.TRULYINBOX_CORE_BASE_URL,
  tempoBaseUrl: process.env.TEMPO_BASE_URL,
  lokiBaseUrl: process.env.LOKI_BASE_URL,
  withStdout: process.env.WITH_STDOUT,
  shClientBaseUrl: process.env.SH_CLIENT_BASE_URL,
});
