import Stripe from 'stripe';
export const STRIPE_CONFIG: Stripe.StripeConfig = {
  apiVersion: '2023-08-16',
};

export const SERVICE_NAME = 'apus';
export const DEFAULT_OTP = '1234';
export const SEND_OTP = false;
export const REQUIRE_LOGIN_OTP = false;
export const RESET_DATA_PIN = '998877';
export const ADMIN_TIMEZONE = `GMT`;
export const ADMIN_DATE_FORMAT = `dd-MM-yyyy`;
export const MAX_FIND_ALL_LIMIT = 50;

export const DATE_SETTINGS = {
  DEFAULT_TZ: 'asia/kolkata',
  DEFAULT_START_TIME: '08:00:00.000',
  DATE_FORMAT: 'yyyy-MM-dd',
  TIME_FORMAT: 'HH:mm:ss',
  DATE_TIME_FORMAT: 'yyyy-MM-dd HH:mm:ss',
  IST_DATE_TIME_FORMAT: 'MMMM dd yyyy, HH:mm a',
  DATE: '2022-12-31',
  TIME: '23:59:59',
  DATE_TIME: '2022-12-31 23:59:59',
  INVALID_DATE: 'Invalid Date',
  INVALID_TIME: 'Invalid Time',
  INVALID_DATE_TIME: 'Invalid Date Time',
  COMPARE_TIME: 'From time can not be grater than to time',
  COMPARE_DATE: 'From date can not be grater than to date',
  FUTURE_DATE: 'Event date must be a future date',
  SHIFT_FUTURE_DATE: 'Shift date time must be a future',
  FUTURE_TIME: 'Event time must be a future time',
  SHIFT_FUTURE_TIME: 'Shift date time must be a future',
  PAST_DATE: 'DOB date must be a past date',
  FUTURE: 'Please enter future date',
  COMPARE_DATE_TIME: 'From date time can not be grater than to date time',
};

export const OTP_SETTINGS = {
  OTP_LENGTH: 4,
  OTP_REF_LENGTH: 6,
  OTP_EXPIRATION_LIMIT: 2, // in minutes
};

export const INVITATION_SETTINGS = {
  TOKEN_LENGTH: 64,
  EXPIRATION_LIMIT: 2880, // in minutes // 48 Hours
};

export const RESET_PASSWORD_SETTINGS = {
  TOKEN_LENGTH: 64,
  EXPIRATION_LIMIT: 2880, // in minutes // 48 Hours
};

export enum STATUS_ENUM {
  ENABLED = 'ENABLED',
  DISABLED = 'DISABLED',
}

export const SH_ACCOUNT_STATUS = {
  deleted: 'Deleted',
  active: 'Active',
  suspended: 'Suspended',
};

export enum ExportTypeEnum {
  CSV,
  PDF,
}

export enum USER_STATUS {
  Active = 1,
  InActive = 0,
  Invited = 2,
  InviteCancelled = 3,
  Deleted = 4,
  Failed = 5,
}

export enum EXPORT_MODULES_ENUM {
  USER = 'USER',
  ACCOUNT = 'ACCOUNT',
  EMAIL_ACCOUNT = 'EMAIL_ACCOUNT',
}

export const COMMON_ERROR_MESSAGES = {
  NOT_FOUND: 'Not Found',
  BLACKLIST_DOMAIN_EXISTS: 'Domain already exists in blacklist',
  BLACKLIST_EMAIL_EXISTS: 'Email already exists in blacklist',
  BLACKLIST_IP_EXISTS: 'IP already exists in blacklist',
  INVALID_CAPTCHA: 'Invalid Captcha',
  INVALID_DATE: 'Invalid Date',
  INVALID_START_DATE: 'Invalid Start Date',
  INVALID_END_DATE: 'Invalid End Date',
  INVALID_OTP_REFERENCE: 'Invalid OTP reference.',
  INVALID_COUNTRY_CODE: 'Invalid Country Code.',
  INVALID_PHONE: 'Invalid Phone Number.',
  COUNTRY_CODE_REQUIRED: 'Country Code can not be blank.',
  PHONE_REQUIRED: 'Phone Number can not be blank.',
  EMAIL_REQUIRED: 'Email can not be blank.',
  COUNTRY_CODE_LENGTH: 'Country Code can not be more than 3 digit.',
  PHONE_LENGTH: 'Phone Number can not be more than 10 digit.',
  PASSWORD_PATTERN_ERROR: `Password must contain at least 1 uppercase letter 1 lowercase letter 1 digit and 1 special character.`,
  INVALID_EMAIL: 'Invalid email address.',
  PASSWORD_MATCH_ERROR: 'Password and confirm password does not match.',
  TOKEN_IS_EXPIRED: 'Password reset link is expired. Please try again',
  NOT_ALLOWED: 'You are not allowed to explore this data.',
  USER_EMAIL_EXISTS: 'User email already exists please enter another.',
  USER_NOT_FOUND: 'User not found.',
  ACCOUNT_NOT_FOUND: 'Account not found.',
  PARENT_PLAN_NOT_FOUND: 'Parent Plan not found.',
  EMAIL_ACCOUNT_NOT_FOUND: 'Email account not found.',
  EMAIL_ACCOUNT_DISCONNECTED: 'Email account already disconnected.',
  ACCOUNT_SUBSCRIPTION_NOT_FOUND: 'Account Subscription not found.',
  PLAN_NOT_FOUND: 'Plan not found.',
  ADMIN_USER_EXISTS: 'Admin User already exists with this email.',
  USER_STATUS_INVITED: 'User status is Invited.',
  USER_STATUS_INACTIVE: 'User status is Inactive.',
  TAG_EXISTS: 'Tag already exists in taglist.',
  TAG_NOT_FOUND: 'Tag not found.',
  TAG_ALREADY_DELETED: 'Tag already deleted.',
  AGENCY_USER_NOT_FOUND: 'Agency User not found.',
  AGENCY_USER_STATUS_INVITED: 'Agency User status is Invited.',
  AGENCY_USER_STATUS_INACTIVE: 'Agency User status is Inactive.',
  ACCOUNT_SUBSCRIPTION_EXISTS: 'Account Subscription Already Exists',
};

export const DEFAULT_EV_CREDIT = 200;
export const DEFAULT_LTD_EMAIL_OUTREACH_PRO_EV_CREDIT = 2000;

export enum METHOD {
  POST = 'post',
  GET = 'get',
  REQUEST = 'request',
}

export const DEFAULT_COLUMN_SETTINGS = {
  USER: [
    { dataIndex: 'firstName', title: 'Name', visible: true },
    { dataIndex: 'id', title: 'User ID', visible: true },
    { dataIndex: 'createdAt', title: 'Sign Up Date', visible: true },
    { dataIndex: 'lastSeen', title: 'Last Login', visible: true },
    { dataIndex: 'trackingId', title: 'Tracking ID', visible: true },
    { dataIndex: 'role', title: 'Role', visible: true },
    { dataIndex: 'currentPlan', title: 'Current Plan', visible: true },
    { dataIndex: 'phone', title: 'Phone', visible: false },
    { dataIndex: 'designation', title: 'Job Role', visible: false },
    { dataIndex: 'useCase', title: 'Use Case', visible: false },
  ],
  ACCOUNT: [
    { dataIndex: 'id', title: 'Account ID', visible: true },
    { dataIndex: 'owner', title: 'Owner', visible: true },
    { dataIndex: 'createdAt', title: 'Created Date', visible: true },
    { dataIndex: 'currentPlan', title: 'Current Plan', visible: true },
    { dataIndex: 'industry', title: 'Industry', visible: true },
    { dataIndex: 'teamSize', title: 'Company Size', visible: true },
    { dataIndex: 'country', title: 'Country', visible: false },
    { dataIndex: 'salesOwner', title: 'Sales Owner', visible: false },
    { dataIndex: 'successOwner', title: 'Success Owner', visible: false },
    { dataIndex: 'accountTags', title: 'Tags', visible: false },
    {
      dataIndex: 'paymentMethod',
      title: 'Payment Method Type',
      visible: false,
    },
    {
      dataIndex: 'renewalType',
      title: 'Renewal Type',
      visible: false,
    },
    {
      dataIndex: 'startAt',
      title: 'Plan Start Date',
      visible: false,
    },
    {
      dataIndex: 'endAt',
      title: 'Plan End Date',
      visible: false,
    },
  ],
  EMAIL: [
    { dataIndex: 'id', title: 'ID', visible: true },
    { dataIndex: 'accountId', title: 'Account ID', visible: true },
    { dataIndex: 'userEmail', title: 'User Email', visible: true },
    { dataIndex: 'senderAccount', title: 'Sender Account', visible: true },
    { dataIndex: 'lastConnected', title: 'Last Connected', visible: true },
    { dataIndex: 'esp', title: 'ESP', visible: true },
    { dataIndex: 'emailSetupScore', title: 'Email Setup Score', visible: true },
    { dataIndex: 'dailyQuota', title: 'Daily Quota', visible: true },
  ],
  LOGS: [
    { dataIndex: 'userId', title: 'User ID', visible: true },
    { dataIndex: 'userEmail', title: 'User Email', visible: true },
    { dataIndex: 'date', title: 'Date', visible: true },
    { dataIndex: 'type', title: 'Type', visible: true },
    { dataIndex: 'description', title: 'Description', visible: true },
    { dataIndex: 'createdBy', title: 'Created By', visible: true },
  ],
  BLACKLIST: [
    { dataIndex: 'domain', title: 'Email or Domain', visible: true },
    { dataIndex: 'type', title: 'Type', visible: true },
    { dataIndex: 'createdAt', title: 'Blacklisted On', visible: true },
    { dataIndex: 'note', title: 'Notes', visible: true },
    { dataIndex: 'user.firstName', title: 'Blacklisted By', visible: true },
  ],
  PLAN: [
    { dataIndex: 'id', title: 'Plan ID', visible: true },
    { dataIndex: 'createdBy', title: 'Created By', visible: true },
    { dataIndex: 'name', title: 'Plan Name', visible: true },
    { dataIndex: 'parentPlan', title: 'Parent Plan', visible: true },
    { dataIndex: 'billingCycle', title: 'Billing Cycle', visible: true },
    { dataIndex: 'amount', title: 'Amount', visible: true },
    { dataIndex: 'prospectLimit', title: 'Prospect Limit', visible: false },
    {
      dataIndex: 'emailLimit',
      title: 'Email Sending Limit',
      visible: false,
    },
    { dataIndex: 'customerCount', title: 'Customer Count', visible: false },
    // { dataIndex: 'stripeId', title: 'Stripe ID', visible: true },
    { dataIndex: 'type', title: 'Type', visible: false },
    { dataIndex: 'createdAt', title: 'Created Date', visible: false },
  ],
};

export const EndpointsExcludeApiActivityLog = [];

export const AUTH_COOKIE_KEY = 'sh-admin';

export type CONNECTION_PAYLOAD = {
  accessToken: string;
  refreshToken: string;
  expiresIn: number;
};

export enum Status {
  Inactive = 0,
  Active = 1,
  InProgress = 2,
}

export enum ADMIN_PANEL_USER_STATUS {
  Enable = 1,
  Disable = 0,
}

export const LtdPlanIds = [7, 8, 27, 28, 29, 30, 31, 32, 33];

export const BasicPlanIds = [21, 24, 52, 53, 54, 55, 77, 80];

export const ATMPlanIds = [
  2,
  3,
  5,
  7,
  8,
  19,
  20,
  23,
  26,
  79, // extra
  82, // extra
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99,
  100,
  101,
];

export const NonATMPlanIds = [
  1,
  17,
  18,
  21,
  22,
  24,
  25,
  77, // extra
  78, // extra
  80,
  81,
];

export enum Permissions {
  // Sequence
  ACCOUNT_SEQUENCE_READ = 'ACCOUNT.SEQUENCE.READ',
  ACCOUNT_SEQUENCE_WRITE = 'ACCOUNT.SEQUENCE.WRITE',
  ACCOUNT_SEQUENCE_UPDATE = 'ACCOUNT.SEQUENCE.UPDATE',
  ACCOUNT_SEQUENCE_DELETE = 'ACCOUNT.SEQUENCE.DELETE',

  TEAM_SEQUENCE_READ = 'TEAM.SEQUENCE.READ',
  TEAM_SEQUENCE_WRITE = 'TEAM.SEQUENCE.WRITE',
  TEAM_SEQUENCE_UPDATE = 'TEAM.SEQUENCE.UPDATE',
  TEAM_SEQUENCE_DELETE = 'TEAM.SEQUENCE.DELETE',

  SEQUENCE_READ = 'SEQUENCE.READ',
  SEQUENCE_PROSPECT_READ = 'SEQUENCE_PROSPECT.READ',
  SEQUENCE_EMAIL_READ = 'SEQUENCE_EMAIL.READ',
  SEQUENCE_SETTING_READ = 'SEQUENCE_SETTING.READ',
  SEQUENCE_SETTING_WRITE = 'SEQUENCE_SETTING.WRITE',
  SEQUENCE_SETTING_UPDATE = 'SEQUENCE_SETTING.UPDATE',
  SEQUENCE_SETTING_DELETE = 'SEQUENCE_SETTING.DELETE',
  SEQUENCE_WRITE = 'SEQUENCE.WRITE',
  SEQUENCE_DELETE = 'SEQUENCE.DELETE',
  SEQUENCE_UPDATE = 'SEQUENCE.UPDATE',
  DRAFT_SEQUENCE_READ = 'DRAFT_SEQUENCE.READ',

  TEAM_SEQUENCE_SETTING_READ = 'TEAM.SEQUENCE_SETTING.READ',
  TEAM_SEQUENCE_SETTING_WRITE = 'TEAM.SEQUENCE_SETTING.WRITE',
  TEAM_SEQUENCE_SETTING_UPDATE = 'TEAM.SEQUENCE_SETTING.UPDATE',
  TEAM_SEQUENCE_SETTING_DELETE = 'TEAM.SEQUENCE_SETTING.DELETE',

  ACCOUNT_SEQUENCE_SETTING_READ = 'ACCOUNT.SEQUENCE_SETTING.READ',
  ACCOUNT_SEQUENCE_SETTING_WRITE = 'ACCOUNT.SEQUENCE_SETTING.WRITE',
  ACCOUNT_SEQUENCE_SETTING_UPDATE = 'ACCOUNT.SEQUENCE_SETTING.UPDATE',
  ACCOUNT_SEQUENCE_SETTING_DELETE = 'ACCOUNT.SEQUENCE_SETTING.DELETE',

  // Sequence Step
  TEAM_SEQUENCE_STEP_READ = 'TEAM.SEQUENCE_STEP.READ',
  TEAM_SEQUENCE_STEP_WRITE = 'TEAM.SEQUENCE_STEP.WRITE',
  TEAM_SEQUENCE_STEP_UPDATE = 'TEAM.SEQUENCE_STEP.UPDATE',
  TEAM_SEQUENCE_STEP_DELETE = 'TEAM.SEQUENCE_STEP.DELETE',

  ACCOUNT_SEQUENCE_STEP_READ = 'ACCOUNT.SEQUENCE_STEP.READ',
  ACCOUNT_SEQUENCE_STEP_WRITE = 'ACCOUNT.SEQUENCE_STEP.WRITE',
  ACCOUNT_SEQUENCE_STEP_UPDATE = 'ACCOUNT.SEQUENCE_STEP.UPDATE',
  ACCOUNT_SEQUENCE_STEP_DELETE = 'ACCOUNT.SEQUENCE_STEP.DELETE',

  SEQUENCE_STEP_READ = 'SEQUENCE_STEP.READ',
  SEQUENCE_STEP_WRITE = 'SEQUENCE_STEP.WRITE',
  SEQUENCE_STEP_UPDATE = 'SEQUENCE_STEP.UPDATE',
  SEQUENCE_STEP_DELETE = 'SEQUENCE_STEP.DELETE',

  // Sequence Step Variant
  TEAM_SEQUENCE_STEP_VARIANT_READ = 'TEAM.SEQUENCE_STEP_VARIANT.READ',
  TEAM_SEQUENCE_STEP_VARIANT_WRITE = 'TEAM.SEQUENCE_STEP_VARIANT.WRITE',
  TEAM_SEQUENCE_STEP_VARIANT_UPDATE = 'TEAM.SEQUENCE_STEP_VARIANT.UPDATE',
  TEAM_SEQUENCE_STEP_VARIANT_DELETE = 'TEAM.SEQUENCE_STEP_VARIANT.DELETE',

  ACCOUNT_SEQUENCE_STEP_VARIANT_READ = 'ACCOUNT.SEQUENCE_STEP_VARIANT.READ',
  ACCOUNT_SEQUENCE_STEP_VARIANT_WRITE = 'ACCOUNT.SEQUENCE_STEP_VARIANT.WRITE',
  ACCOUNT_SEQUENCE_STEP_VARIANT_UPDATE = 'ACCOUNT.SEQUENCE_STEP_VARIANT.UPDATE',
  ACCOUNT_SEQUENCE_STEP_VARIANT_DELETE = 'ACCOUNT.SEQUENCE_STEP_VARIANT.DELETE',

  SEQUENCE_STEP_VARIANT_READ = 'SEQUENCE_STEP_VARIANT.READ',
  SEQUENCE_STEP_VARIANT_WRITE = 'SEQUENCE_STEP_VARIANT.WRITE',
  SEQUENCE_STEP_VARIANT_UPDATE = 'SEQUENCE_STEP_VARIANT.UPDATE',
  SEQUENCE_STEP_VARIANT_DELETE = 'SEQUENCE_STEP_VARIANT.DELETE',

  // Custom Domain
  TEAM_CUSTOM_DOMAIN_READ = 'TEAM.CUSTOM_DOMAIN.READ',
  TEAM_CUSTOM_DOMAIN_WRITE = 'TEAM.CUSTOM_DOMAIN.WRITE',
  TEAM_CUSTOM_DOMAIN_UPDATE = 'TEAM.CUSTOM_DOMAIN.UPDATE',
  TEAM_CUSTOM_DOMAIN_DELETE = 'TEAM.CUSTOM_DOMAIN.DELETE',

  ACCOUNT_CUSTOM_DOMAIN_READ = 'ACCOUNT.CUSTOM_DOMAIN.READ',
  ACCOUNT_CUSTOM_DOMAIN_WRITE = 'ACCOUNT.CUSTOM_DOMAIN.WRITE',
  ACCOUNT_CUSTOM_DOMAIN_UPDATE = 'ACCOUNT.CUSTOM_DOMAIN.UPDATE',
  ACCOUNT_CUSTOM_DOMAIN_DELETE = 'ACCOUNT.CUSTOM_DOMAIN.DELETE',

  CUSTOM_DOMAIN_READ = 'CUSTOM_DOMAIN.READ',
  CUSTOM_DOMAIN_WRITE = 'CUSTOM_DOMAIN.WRITE',
  CUSTOM_DOMAIN_UPDATE = 'CUSTOM_DOMAIN.UPDATE',
  CUSTOM_DOMAIN_DELETE = 'CUSTOM_DOMAIN.DELETE',

  ACCOUNT_CUSTOM_DOMAIN_EMAIL_ACCOUNT_READ = 'ACCOUNT.CUSTOM_DOMAIN_EMAIL_ACCOUNT.READ',
  ACCOUNT_CUSTOM_DOMAIN_EMAIL_ACCOUNT_UPDATE = 'ACCOUNT.CUSTOM_DOMAIN_EMAIL_ACCOUNT.READ',

  // Schedule
  ACCOUNT_SCHEDULE_READ = 'ACCOUNT.SCHEDULE.READ',
  ACCOUNT_SCHEDULE_WRITE = 'ACCOUNT.SCHEDULE.WRITE',
  ACCOUNT_SCHEDULE_DELETE = 'ACCOUNT.SCHEDULE.DELETE',
  ACCOUNT_SCHEDULE_UPDATE = 'ACCOUNT.SCHEDULE.UPDATE',

  SCHEDULE_READ = 'SCHEDULE.READ',
  SCHEDULE_WRITE = 'SCHEDULE.WRITE',
  SCHEDULE_DELETE = 'SCHEDULE.DELETE',
  SCHEDULE_UPDATE = 'SCHEDULE.UPDATE',

  TEAM_SCHEDULE_READ = 'TEAM.SCHEDULE.READ',
  TEAM_SCHEDULE_WRITE = 'TEAM.SCHEDULE.WRITE',
  TEAM_SCHEDULE_DELETE = 'TEAM.SCHEDULE.DELETE',
  TEAM_SCHEDULE_UPDATE = 'TEAM.SCHEDULE.UPDATE',

  // User
  ACCOUNT_USER_READ = 'ACCOUNT.USER.READ',
  ACCOUNT_USER_INVITE = 'ACCOUNT.USER.INVITE',
  ACCOUNT_USER_DELETE = 'ACCOUNT.USER.DELETE',
  ACCOUNT_USER_UPDATE = 'ACCOUNT.USER.UPDATE',
  TEAM_USER_READ = 'TEAM.USER.READ',
  USER_READ = 'USER.READ',
  LTD_ADMIN_PURCHASE_LINK = 'LTD.ADMIN.PURCHASE.LINK',

  // Prospect
  PROSPECT_READ = 'PROSPECT.READ',
  PROSPECT_WRITE = 'PROSPECT.WRITE',
  PROSPECT_UPDATE = 'PROSPECT.UPDATE',
  PROSPECT_DELETE = 'PROSPECT.DELETE',

  TEAM_PROSPECT_READ = 'TEAM.PROSPECT.READ',
  TEAM_PROSPECT_WRITE = 'TEAM.PROSPECT.WRITE',
  TEAM_PROSPECT_UPDATE = 'TEAM.PROSPECT.UPDATE',
  TEAM_PROSPECT_DELETE = 'TEAM.PROSPECT.DELETE',

  ACCOUNT_PROSPECT_READ = 'ACCOUNT.PROSPECT.READ',
  ACCOUNT_PROSPECT_WRITE = 'ACCOUNT.PROSPECT.WRITE',
  ACCOUNT_PROSPECT_UPDATE = 'ACCOUNT.PROSPECT.UPDATE',
  ACCOUNT_PROSPECT_DELETE = 'ACCOUNT.PROSPECT.DELETE',

  // Fields
  ACCOUNT_FIELD_READ = 'ACCOUNT.FIELD.READ',
  ACCOUNT_FIELD_WRITE = 'ACCOUNT.FIELD.WRITE',
  ACCOUNT_FIELD_UPDATE = 'ACCOUNT.FIELD.UPDATE',
  ACCOUNT_FIELD_DELETE = 'ACCOUNT.FIELD.DELETE',

  TEAM_FIELD_READ = 'TEAM.FIELD.READ',
  TEAM_FIELD_WRITE = 'TEAM.FIELD.WRITE',
  TEAM_FIELD_UPDATE = 'TEAM.FIELD.UPDATE',
  TEAM_FIELD_DELETE = 'TEAM.FIELD.DELETE',

  FIELD_READ = 'FIELD.READ',
  FIELD_WRITE = 'FIELD.WRITE',
  FIELD_UPDATE = 'FIELD.UPDATE',
  FIELD_DELETE = 'FIELD.DELETE',

  // TEMPLATE
  ACCOUNT_TEMPLATE_READ = 'ACCOUNT.TEMPLATE.READ',
  ACCOUNT_TEMPLATE_WRITE = 'ACCOUNT.TEMPLATE.WRITE',
  ACCOUNT_TEMPLATE_UPDATE = 'ACCOUNT.TEMPLATE.UPDATE',
  ACCOUNT_TEMPLATE_DELETE = 'ACCOUNT.TEMPLATE.DELETE',

  TEAM_TEMPLATE_READ = 'TEAM.TEMPLATE.READ',
  TEAM_TEMPLATE_WRITE = 'TEAM.TEMPLATE.WRITE',
  TEAM_TEMPLATE_UPDATE = 'TEAM.TEMPLATE.UPDATE',
  TEAM_TEMPLATE_DELETE = 'TEAM.TEMPLATE.DELETE',

  TEMPLATE_READ = 'TEMPLATE.READ',
  TEMPLATE_WRITE = 'TEMPLATE.WRITE',
  TEMPLATE_UPDATE = 'TEMPLATE.UPDATE',
  TEMPLATE_DELETE = 'TEMPLATE.DELETE',

  // Report
  REPORT_READ = 'REPORT.READ',

  // EMAIL
  ACCOUNT_EMAIL_READ = 'ACCOUNT.EMAIL.READ',
  ACCOUNT_EMAIL_WRITE = 'ACCOUNT.EMAIL.WRITE',
  ACCOUNT_EMAIL_UPDATE = 'ACCOUNT.EMAIL.UPDATE',
  ACCOUNT_EMAIL_DELETE = 'ACCOUNT.EMAIL.DELETE',

  TEAM_EMAIL_READ = 'TEAM.EMAIL.READ',
  TEAM_EMAIL_WRITE = 'TEAM.EMAIL.WRITE',
  TEAM_EMAIL_UPDATE = 'TEAM.EMAIL.UPDATE',
  TEAM_EMAIL_DELETE = 'TEAM.EMAIL.DELETE',

  EMAIL_READ = 'EMAIL.READ',
  EMAIL_WRITE = 'EMAIL.WRITE',
  EMAIL_UPDATE = 'EMAIL.UPDATE',
  EMAIL_DELETE = 'EMAIL.DELETE',

  TEAM_EMAIL_ACCOUNT_WRITE = 'TEAM.EMAIL_ACCOUNT.WRITE',
  TEAM_EMAIL_ACCOUNT_READ = 'TEAM.EMAIL_ACCOUNT.READ',
  TEAM_EMAIL_ACCOUNT_UPDATE = 'TEAM.EMAIL_ACCOUNT.UPDATE',
  TEAM_EMAIL_ACCOUNT_DELETE = 'TEAM.EMAIL_ACCOUNT.DELETE',
  TEAM_EMAIL_ACCOUNT_CONNECT = 'TEAM.EMAIL_ACCOUNT.CONNECT',
  TEAM_EMAIL_ACCOUNT_DISCONNECT = 'TEAM.EMAIL_ACCOUNT.DISCONNECT',

  ACCOUNT_EMAIL_ACCOUNT_WRITE = 'ACCOUNT.EMAIL_ACCOUNT.WRITE',
  ACCOUNT_EMAIL_ACCOUNT_READ = 'ACCOUNT.EMAIL_ACCOUNT.READ',
  ACCOUNT_EMAIL_ACCOUNT_UPDATE = 'ACCOUNT.EMAIL_ACCOUNT.UPDATE',
  ACCOUNT_EMAIL_ACCOUNT_DELETE = 'ACCOUNT.EMAIL_ACCOUNT.DELETE',
  ACCOUNT_EMAIL_ACCOUNT_CONNECT = 'ACCOUNT.EMAIL_ACCOUNT.CONNECT',
  ACCOUNT_EMAIL_ACCOUNT_DISCONNECT = 'ACCOUNT.EMAIL_ACCOUNT.DISCONNECT',

  EMAIL_ACCOUNT_WRITE = 'EMAIL_ACCOUNT.WRITE',
  EMAIL_ACCOUNT_READ = 'EMAIL_ACCOUNT.READ',
  EMAIL_ACCOUNT_UPDATE = 'EMAIL_ACCOUNT.UPDATE',
  EMAIL_ACCOUNT_DELETE = 'EMAIL_ACCOUNT.DELETE',
  EMAIL_ACCOUNT_CONNECT = 'EMAIL_ACCOUNT.CONNECT',
  EMAIL_ACCOUNT_DISCONNECT = 'EMAIL_ACCOUNT.DISCONNECT',

  MAILBOX_EMAIL_READ = 'MAILBOX_EMAIL.READ',
  MAILBOX_EMAIL_WRITE = 'MAILBOX_EMAIL.WRITE',
  MAILBOX_EMAIL_UPDATE = 'MAILBOX_EMAIL.UPDATE',

  MAILBOX_CREATE = 'MAILBOX.CREATE',
  MAILBOX_UPDATE = 'MAILBOX.UPDATE',
  EMAIL_WARMUP_READ = 'EMAIL.WARMUP.READ',
  EMAIL_WARMUP_SETTINGS_UPDATE = 'EMAIL.WARMUP_SETTINGS.UPDATE',
  ACCOUNT_BUSINESS_EMAILS = 'ACCOUNT.BUSINESS_EMAILS.READ',

  // Subscription
  ACCOUNT_SUBSCRIPTION_CREATE = 'ACCOUNT.SUBSCRIPTION.CREATE',
  ACCOUNT_SUBSCRIPTION_UPDATE = 'ACCOUNT.SUBSCRIPTION.UPDATE',
  ACCOUNT_SUBSCRIPTION_READ = 'ACCOUNT.SUBSCRIPTION.READ',

  // Blacklist Domains
  ACCOUNT_BLACKLISTED_DOMAIN_WRITE = 'ACCOUNT.BLACKLISTED_DOMAIN.WRITE',
  ACCOUNT_BLACKLISTED_DOMAIN_READ = 'ACCOUNT.BLACKLISTED_DOMAIN.READ',
  ACCOUNT_BLACKLISTED_DOMAIN_DELETE = 'ACCOUNT.BLACKLISTED_DOMAIN.DELETE',

  BLACKLISTED_DOMAIN_WRITE = 'BLACKLISTED_DOMAIN.WRITE',
  BLACKLISTED_DOMAIN_READ = 'BLACKLISTED_DOMAIN.READ',
  BLACKLISTED_DOMAIN_UPDATE = 'BLACKLISTED_DOMAIN.UPDATE',
  BLACKLISTED_DOMAIN_DELETE = 'BLACKLISTED_DOMAIN.DELETE',

  TEAM_BLACKLISTED_DOMAIN_WRITE = 'TEAM.BLACKLISTED_DOMAIN.WRITE',
  TEAM_BLACKLISTED_DOMAIN_READ = 'TEAM.BLACKLISTED_DOMAIN.READ',
  TEAM_BLACKLISTED_DOMAIN_UPDATE = 'TEAM.BLACKLISTED_DOMAIN.UPDATE',
  TEAM_BLACKLISTED_DOMAIN_DELETE = 'TEAM.BLACKLISTED_DOMAIN.DELETE',

  // Api Token
  ACCOUNT_API_TOKEN_WRITE = 'ACCOUNT.API_TOKEN.WRITE',
  ACCOUNT_API_TOKEN_READ = 'ACCOUNT.API_TOKEN.READ',
  ACCOUNT_API_TOKEN_DELETE = 'ACCOUNT.API_TOKEN.DELETE',

  TEAM_API_TOKEN_WRITE = 'TEAM.API_TOKEN.WRITE',
  TEAM_API_TOKEN_READ = 'TEAM.API_TOKEN.READ',
  TEAM_API_TOKEN_DELETE = 'TEAM.API_TOKEN.DELETE',

  API_TOKEN_WRITE = 'API_TOKEN.WRITE',
  API_TOKEN_READ = 'API_TOKEN.READ',
  API_TOKEN_DELETE = 'API_TOKEN.DELETE',

  // Notifications
  NOTIFICATION_READ = 'NOTIFICATION.READ',
  NOTIFICATION_UPDATE = 'NOTIFICATION.UPDATE',
  NOTIFICATION_DELETE = 'NOTIFICATION.DELETE',

  // EV-Credits
  ACCOUNT_EV_CREDIT_WRITE = 'ACCOUNT.EV_CREDIT.WRITE',
  EV_CREDIT_READ = 'EV_CREDIT.READ',

  // My-Profile
  MY_PROFILE_READ = 'MY_PROFILE.READ',
  MY_PROFILE_UPDATE = 'MY_PROFILE.UPDATE',

  // Setting
  SETTING_READ = 'SETTING.READ',

  // Chrome-Extentation
  CHROME_EXTENSION_READ = 'CHROME_EXTENSION.READ',

  // Agency
  AGENCY_USER_READ = 'AGENCY.USER.READ',
  AGENCY_CLIENT_ASSIGN = 'AGENCY.CLIENT.ASSIGN',
  AGENCY_USER_UPDATE = 'AGENCY.USER.UPDATE',
  AGENCY_CLIENT_UPDATE = 'AGENCY.CLIENT.UPDATE',
  AGENCY_CLIENT_READ = 'AGENCY.CLIENT.READ',
  AGENCY_CLIENT_CREATE = 'AGENCY.CLIENT.CREATE',
  ACCOUNT_ADMIN_CREATE = 'ACCOUNT.ADMIN.CREATE',
  AGENCY_USER_INVITE = 'AGENCY.USER.INVITE',
  AGENCY_CLIENT_DELETE = 'AGENCY.CLIENT.DELETE',
  AGENCY_USER_DELETE = 'AGENCY.USER.DELETE',
  ACCOUNT_CLIENT_READ = 'ACCOUNT.CLIENT.READ',
  AGENCY_ADMIN_UPDATE = 'AGENCY.ADMIN.UPDATE',
  CREATE_AGENCY = 'CREATE.AGENCY',

  // On-boarding Form Fields
  ONBOARDING_INDUSTRY_WRITE = 'ONBOARDING.INDUSTRY.WRITE',
  ONBOARDING_JOB_ROLE_WRITE = 'ONBOARDING.JOB_ROLE.WRITE',
  ONBOARDING_USE_CASE_WRITE = 'ONBOARDING.USE_CASE.WRITE',
  ONBOARDING_COMPANY_SIZE_WRITE = 'ONBOARDING.COMPANY_SIZE.WRITE',
  CREATE_ONBOARDING_EV_CREDITS = 'CREATE.ONBOARDING.EV.CREDITS',
  ONBOARDING_STEP_UPGRADE = 'ONBOARDING.STEP.UPGRADE',

  // Admin Panel
  ALL_EMAIL_ACCOUNT_UPDATE = 'ALL.EMAIL_ACCOUNT.UPDATE',
  ALL_USER_DELETE = 'ALL.USER.DELETE',
  ALL_EV_CREDIT_UPDATE = 'ALL.EV_CREDIT.UPDATE',
  ALL_USER_UPDATE = 'ALL.USER.UPDATE',
  ALL_EMAIL_ACCOUNT_CONNECT = 'ALL.EMAIL_ACCOUNT.CONNECT',
  CREATE_NEW_PLAN = 'PLAN.CREATE',
  ALL_BILLING_SYNC = 'ALL.BILLING.SYNC',
  ALL_TAGS_DELETE = 'ALL.TAGS.DELETE',
  ALL_WARMUP_STATUS_UPDATE = 'ALL.WARMUP_STATUS.UPDATE',
  ALL_PAUSE_SEQUENCE_BOUNCE_EMAIL = 'ALL.PAUSE_SEQUENCE_BOUNCE_EMAIL',

  // Attachment
  ACCOUNT_ATTACHMENT_READ = 'ACCOUNT.ATTACHMENT.READ',
  TEAM_ATTACHMENT_READ = 'TEAM.ATTACHMENT.READ',
  ATTACHMENT_READ = 'ATTACHMENT.READ',
  ACCOUNT_ATTACHMENT_DELETE = 'ACCOUNT.ATTACHMENT.DELETE',
  TEAM_ATTACHMENT_DELETE = 'TEAM.ATTACHMENT.DELETE',
  ATTACHMENT_DELETE = 'ATTACHMENT.DELETE',
  ALL_SUBSCRIPTION_UPDATE = 'ALL.SUBSCRIPTION.UPDATE',
  ALL_USER_READ = 'ALL.USER.READ',

  // Unibox
  UNIBOX_THREAD_READ = 'UNIBOX_THREAD.READ',
  UNIBOX_EMAIL_ACTIVITY_READ = 'UNIBOX_EMAIL_ACTIVITY.READ',
  UNIBOX_REPLY = 'UNIBOX.REPLY',
  UNIBOX_FORWARD = 'UNIBOX.FORWARD',
  UNIBOX_SEQUENCES_READ = 'UNIBOX_SEQUENCES.READ',
  UNIBOX_EMAIL_ACCOUNTS_READ = 'UNIBOX_EMAIL_ACCOUNTS.READ',
  UNIBOX_CATEGORY_UPDATE = 'UNIBOX_CATEGORY.UPDATE',
  UNIBOX_READ_STATUS_UPDATE = 'UNIBOX_READ_STATUS.UPDATE',
  UNIBOX_EMAIL_THREAD_DELETE = 'UNIBOX_EMAIL_THREAD.DELETE',
  UNIBOX_THREAD_UNLIMITED = 'UNIBOX_THREAD.UNLIMITED', // frontend

  TEAM_UNIBOX_THREAD_READ = 'TEAM.UNIBOX_THREAD.READ',
  TEAM_UNIBOX_EMAIL_ACTIVITY_READ = 'TEAM.UNIBOX_EMAIL_ACTIVITY.READ',
  TEAM_UNIBOX_REPLY = 'TEAM.UNIBOX.REPLY',
  TEAM_UNIBOX_FORWARD = 'TEAM.UNIBOX.FORWARD',
  TEAM_UNIBOX_SEQUENCES_READ = 'TEAM.UNIBOX_SEQUENCES.READ',
  TEAM_UNIBOX_EMAIL_ACCOUNTS_READ = 'TEAM.UNIBOX_EMAIL_ACCOUNTS.READ',
  TEAM_UNIBOX_CATEGORY_UPDATE = 'TEAM.UNIBOX_CATEGORY.UPDATE',
  TEAM_UNIBOX_READ_STATUS_UPDATE = 'TEAM.UNIBOX_READ_STATUS.UPDATE',
  TEAM_UNIBOX_EMAIL_THREAD_DELETE = 'TEAM.UNIBOX_EMAIL_THREAD.DELETE',

  ACCOUNT_UNIBOX_THREAD_READ = 'ACCOUNT.UNIBOX_THREAD.READ',
  ACCOUNT_UNIBOX_EMAIL_ACTIVITY_READ = 'ACCOUNT.UNIBOX_EMAIL_ACTIVITY.READ',
  ACCOUNT_UNIBOX_REPLY = 'ACCOUNT.UNIBOX.REPLY',
  ACCOUNT_UNIBOX_FORWARD = 'ACCOUNT.UNIBOX.FORWARD',
  ACCOUNT_UNIBOX_SEQUENCES_READ = 'ACCOUNT.UNIBOX_SEQUENCES.READ',
  ACCOUNT_UNIBOX_EMAIL_ACCOUNTS_READ = 'ACCOUNT.UNIBOX_EMAIL_ACCOUNTS.READ',
  ACCOUNT_UNIBOX_CATEGORY_UPDATE = 'ACCOUNT.UNIBOX_CATEGORY.UPDATE',
  ACCOUNT_UNIBOX_READ_STATUS_UPDATE = 'ACCOUNT.UNIBOX_READ_STATUS.UPDATE',
  ACCOUNT_UNIBOX_EMAIL_THREAD_DELETE = 'ACCOUNT.UNIBOX_EMAIL_THREAD.DELETE',

  // Inbox Rotation User Access List
  UPDATE_INBOX_ROTATION_USER_ACCESS_LIST = 'INBOX_ROTATION_USER_ACCESS_LIST.UPDATE',

  ACCOUNT_TAG_WRITE = 'ACCOUNT.TAG.WRITE',
  ACCOUNT_TAG_READ = 'ACCOUNT.TAG.READ',
  ACCOUNT_TAG_UPDATE = 'ACCOUNT.TAG.UPDATE',
  ACCOUNT_TAG_DELETE = 'ACCOUNT.TAG.DELETE',

  TEAM_TAG_WRITE = 'TEAM.TAG.WRITE',
  TEAM_TAG_READ = 'TEAM.TAG.READ',
  TEAM_TAG_UPDATE = 'TEAM.TAG.UPDATE',
  TEAM_TAG_DELETE = 'TEAM.TAG.DELETE',

  TAG_DELETE = 'TAG.DELETE',

  API_KEY_WRITE = 'API_KEY.WRITE',
  API_KEY_READ = 'API_KEY.READ',
  API_KEY_UPDATE = 'API_KEY.UPDATE',
  API_KEY_DELETE = 'API_KEY.DELETE',

  TEAM_API_KEY_WRITE = 'TEAM.API_KEY.WRITE',
  TEAM_API_KEY_READ = 'TEAM.API_KEY.READ',
  TEAM_API_KEY_UPDATE = 'TEAM.API_KEY.UPDATE',
  TEAM_API_KEY_DELETE = 'TEAM.API_KEY.DELETE',

  TEAM_SHOW = 'TEAM.SHOW',
  ACCOUNT_TEAM_WRITE = 'ACCOUNT.TEAM.WRITE',
  ACCOUNT_TEAM_READ = 'ACCOUNT.TEAM.READ',
  ACCOUNT_TEAM_UPDATE = 'ACCOUNT.TEAM.UPDATE',
  ACCOUNT_TEAM_DELETE = 'ACCOUNT.TEAM.DELETE',

  ACCOUNT_TEAM_INVITE_WRITE = 'ACCOUNT.TEAM_INVITE.WRITE',
  ACCOUNT_TEAM_INVITE_READ = 'ACCOUNT.TEAM_INVITE.READ',
  ACCOUNT_TEAM_INVITE_UPDATE = 'ACCOUNT.TEAM_INVITE.UPDATE',
  ACCOUNT_TEAM_INVITE_DELETE = 'ACCOUNT.TEAM_INVITE.DELETE',

  TEAM_TEAM_INVITE_WRITE = 'TEAM.TEAM_INVITE.WRITE',
  TEAM_TEAM_INVITE_READ = 'TEAM.TEAM_INVITE.READ',
  TEAM_TEAM_INVITE_UPDATE = 'TEAM.TEAM_INVITE.UPDATE',
  TEAM_TEAM_INVITE_DELETE = 'TEAM.TEAM_INVITE.DELETE',

  ACCOUNT_API_KEY_READ = 'ACCOUNT.API_KEY.READ',
  ACCOUNT_API_KEY_UPDATE = 'ACCOUNT.API_KEY.UPDATE',
  ACCOUNT_API_KEY_DELETE = 'ACCOUNT.API_KEY.DELETE',

  ACCOUNT_ADMIN_SETTING_WRITE = 'ACCOUNT.ADMIN_SETTING.WRITE',
  ACCOUNT_ADMIN_SETTING_READ = 'ACCOUNT.ADMIN_SETTING.READ',
  ACCOUNT_ADMIN_SETTING_UPDATE = 'ACCOUNT.ADMIN_SETTING.UPDATE',
  ACCOUNT_ADMIN_SETTING_DELETE = 'ACCOUNT.ADMIN_SETTING.DELETE',

  EMAIL_ACCOUNT_SETTINGS_READ = 'EMAIL_ACCOUNT_SETTINGS.READ',
  EMAIL_ACCOUNT_SETTINGS_WRITE = 'EMAIL_ACCOUNT_SETTINGS.WRITE',
  EMAIL_ACCOUNT_SETTINGS_UPDATE = 'EMAIL_ACCOUNT_SETTINGS.UPDATE',
  EMAIL_ACCOUNT_SETTINGS_DELETE = 'EMAIL_ACCOUNT_SETTINGS.DELETE',

  ACCOUNT_EMAIL_ACCOUNT_SETTINGS_READ = 'ACCOUNT.EMAIL_ACCOUNT_SETTINGS.READ',
  ACCOUNT_EMAIL_ACCOUNT_SETTINGS_WRITE = 'ACCOUNT.EMAIL_ACCOUNT_SETTINGS.WRITE',
  ACCOUNT_EMAIL_ACCOUNT_SETTINGS_UPDATE = 'ACCOUNT.EMAIL_ACCOUNT_SETTINGS.UPDATE',
  ACCOUNT_EMAIL_ACCOUNT_SETTINGS_DELETE = 'ACCOUNT.EMAIL_ACCOUNT_SETTINGS.DELETE',

  TEAM_EMAIL_ACCOUNT_SETTINGS_READ = 'TEAM.EMAIL_ACCOUNT_SETTINGS.READ',
  TEAM_EMAIL_ACCOUNT_SETTINGS_WRITE = 'TEAM.EMAIL_ACCOUNT_SETTINGS.WRITE',
  TEAM_EMAIL_ACCOUNT_SETTINGS_UPDATE = 'TEAM.EMAIL_ACCOUNT_SETTINGS.UPDATE',
  TEAM_EMAIL_ACCOUNT_SETTINGS_DELETE = 'TEAM.EMAIL_ACCOUNT_SETTINGS.DELETE',

  ACCOUNT_TEAM_MEMBER_READ = 'ACCOUNT.TEAM_MEMBER.READ',
  ACCOUNT_TEAM_MEMBER_WRITE = 'ACCOUNT.TEAM_MEMBER.WRITE',
  ACCOUNT_TEAM_MEMBER_UPDATE = 'ACCOUNT.TEAM_MEMBER.UPDATE',
  ACCOUNT_TEAM_MEMBER_DELETE = 'ACCOUNT.TEAM_MEMBER.DELETE',

  TEAM_MEMBER_READ = 'TEAM_MEMBER.READ',
  TEAM_MEMBER_WRITE = 'TEAM_MEMBER.WRITE',
  TEAM_MEMBER_UPDATE = 'TEAM_MEMBER.UPDATE',
  TEAM_MEMBER_DELETE = 'TEAM_MEMBER.DELETE',

  TEAM_TEAM_MEMBER_WRITE = 'TEAM.TEAM_MEMBER.WRITE',
  TEAM_TEAM_MEMBER_READ = 'TEAM.TEAM_MEMBER.READ',
  TEAM_TEAM_MEMBER_UPDATE = 'TEAM.TEAM_MEMBER.UPDATE',
  TEAM_TEAM_MEMBER_DELETE = 'TEAM.TEAM_MEMBER.DELETE',
  SEQUENCE_SCORE_READ = 'SEQUENCE.SCORE.READ',

  // Change Login Email
  CREDENTIALS_UPDATE = 'CREDENTIALS.UPDATE',
  TAG_WRITE = 'TAG.WRITE',
  TAG_READ = 'TAG.READ',
  TAG_UPDATE = 'TAG.UPDATE',
}

export const ProspectSharingPermissions: string[] = [
  Permissions.ACCOUNT_PROSPECT_READ,
  Permissions.ACCOUNT_PROSPECT_UPDATE,
  Permissions.ACCOUNT_PROSPECT_DELETE,
  Permissions.ACCOUNT_PROSPECT_WRITE,
];

export enum RedisCacheKey {
  ATMAccountAccessibleUserIds = 'atm-account-accesible-user-ids',
  ATMAccountPermissions = 'atm-account-permissions',
  ATMTeamAccessibleUserIds = 'atm-team-accesible-user-ids',
  ATMTeamPermissions = 'atm-team-permissions',
  ATMUserTeams = 'atm-user-teams',
}
